import '../models/medication.dart';
import '../models/pharmacy.dart';
import '../models/review.dart';

class MockDataService {
  // ─── Medications ────────────────────────────────────────────
  static List<Medication> getMedications() => [
    Medication(
      id: 1,
      barcode: '1234567890001',
      regNumber: 'REG001',
      tradeName: 'Panadol',
      genericName: 'Paracetamol',
      dosage: '500mg',
      form: 'Tablet',
      manufacturer: 'GSK',
      category: 'Pain Relief',
      mophCeiling: 2.50,
      createdAt: DateTime(2024, 1, 15),
      updatedAt: DateTime(2024, 4, 10),
      isBlocked: false,
    ),
    Medication(
      id: 2,
      barcode: '1234567890002',
      regNumber: 'REG002',
      tradeName: 'Augmentin',
      genericName: 'Amoxicillin/Clavulanate',
      dosage: '625mg',
      form: 'Tablet',
      manufacturer: 'GSK',
      category: 'Antibiotics',
      mophCeiling: 12.00,
      createdAt: DateTime(2024, 1, 20),
      updatedAt: DateTime(2024, 4, 10),
      isBlocked: false,
    ),
    Medication(
      id: 3,
      barcode: '1234567890003',
      regNumber: 'REG003',
      tradeName: 'Glucophage',
      genericName: 'Metformin',
      dosage: '850mg',
      form: 'Tablet',
      manufacturer: 'Merck',
      category: 'Diabetes',
      mophCeiling: 8.00,
      createdAt: DateTime(2024, 1, 25),
      updatedAt: DateTime(2024, 4, 10),
      isBlocked: false,
    ),
    Medication(
      id: 4,
      barcode: '1234567890004',
      regNumber: 'REG004',
      tradeName: 'Lipitor',
      genericName: 'Atorvastatin',
      dosage: '20mg',
      form: 'Tablet',
      manufacturer: 'Pfizer',
      category: 'Cardiovascular',
      mophCeiling: 15.00,
      createdAt: DateTime(2024, 1, 30),
      updatedAt: DateTime(2024, 4, 10),
      isBlocked: false,
    ),
    Medication(
      id: 5,
      barcode: '1234567890005',
      regNumber: 'REG005',
      tradeName: 'Ventolin',
      genericName: 'Salbutamol',
      dosage: '100mcg',
      form: 'Inhaler',
      manufacturer: 'GSK',
      category: 'Respiratory',
      mophCeiling: 5.50,
      createdAt: DateTime(2024, 2, 5),
      updatedAt: DateTime(2024, 4, 10),
      isBlocked: false,
    ),
    Medication(
      id: 6,
      barcode: '1234567890006',
      regNumber: 'REG006',
      tradeName: 'Zithromax',
      genericName: 'Azithromycin',
      dosage: '500mg',
      form: 'Tablet',
      manufacturer: 'Pfizer',
      category: 'Antibiotics',
      mophCeiling: 10.00,
      createdAt: DateTime(2024, 2, 10),
      updatedAt: DateTime(2024, 4, 10),
      isBlocked: false,
    ),
    Medication(
      id: 7,
      barcode: '1234567890007',
      regNumber: 'REG007',
      tradeName: 'Nexium',
      genericName: 'Esomeprazole',
      dosage: '40mg',
      form: 'Capsule',
      manufacturer: 'AstraZeneca',
      category: 'Gastrointestinal',
      mophCeiling: 18.00,
      createdAt: DateTime(2024, 2, 15),
      updatedAt: DateTime(2024, 4, 10),
      isBlocked: false,
    ),
    Medication(
      id: 8,
      barcode: '1234567890008',
      regNumber: 'REG008',
      tradeName: 'Crestor',
      genericName: 'Rosuvastatin',
      dosage: '10mg',
      form: 'Tablet',
      manufacturer: 'AstraZeneca',
      category: 'Cardiovascular',
      mophCeiling: 20.00,
      createdAt: DateTime(2024, 2, 20),
      updatedAt: DateTime(2024, 4, 10),
      isBlocked: false,
    ),
    Medication(
      id: 9,
      barcode: '1234567890009',
      regNumber: 'REG009',
      tradeName: 'Brufen',
      genericName: 'Ibuprofen',
      dosage: '400mg',
      form: 'Tablet',
      manufacturer: 'Abbott',
      category: 'Pain Relief',
      mophCeiling: 3.00,
      createdAt: DateTime(2024, 2, 25),
      updatedAt: DateTime(2024, 4, 10),
      isBlocked: false,
    ),
    Medication(
      id: 10,
      barcode: '1234567890010',
      regNumber: 'REG010',
      tradeName: 'Concor',
      genericName: 'Bisoprolol',
      dosage: '5mg',
      form: 'Tablet',
      manufacturer: 'Merck',
      category: 'Cardiovascular',
      mophCeiling: 11.00,
      createdAt: DateTime(2024, 3, 5),
      updatedAt: DateTime(2024, 4, 10),
      isBlocked: false,
    ),
    Medication(
      id: 11,
      barcode: '1234567890011',
      regNumber: 'REG011',
      tradeName: 'Amoxil',
      genericName: 'Amoxicillin',
      dosage: '500mg',
      form: 'Capsule',
      manufacturer: 'GSK',
      category: 'Antibiotics',
      mophCeiling: 4.50,
      createdAt: DateTime(2024, 3, 10),
      updatedAt: DateTime(2024, 4, 10),
      isBlocked: false,
    ),
    Medication(
      id: 12,
      barcode: '1234567890012',
      regNumber: 'REG012',
      tradeName: 'Cataflam',
      genericName: 'Diclofenac Potassium',
      dosage: '50mg',
      form: 'Tablet',
      manufacturer: 'Novartis',
      category: 'Pain Relief',
      mophCeiling: 6.00,
      createdAt: DateTime(2024, 3, 15),
      updatedAt: DateTime(2024, 4, 10),
      isBlocked: false,
    ),
  ];

  // ─── Pharmacies ─────────────────────────────────────────────
  static List<Pharmacy> getPharmacies() {
    return [
      Pharmacy(
        id: 1,
        name: 'Al-Hayat Pharmacy',
        location: 'Hamra Street, Beirut',
        licenseNumber: 'LIC001',
        hwid: 'HWID001',
        region: 'Mount Lebanon',
        status: 'online',
        lastSeen: 'just now',
        latencyMs: 45,
        syncVersion: '2.6.1',
        syncPct: 100,
        createdAt: DateTime(2024, 1, 10),
        latitude: 33.8938,
        longitude: 35.5018,
        phone: '+961 1 350 000',
        rating: 4.5,
        reviewCount: 128,
        openingHours: '08:00',
        closingHours: '22:00',
        isOpen: true,
        distanceKm: 0.8,
        stock: [
          PharmacyStock(
            medicationId: 1,
            medicationName: 'Panadol',
            inStock: true,
            currentPrice: 2.50,
            ministryLockedPrice: 2.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 2)),
          ),
          PharmacyStock(
            medicationId: 2,
            medicationName: 'Augmentin',
            inStock: true,
            currentPrice: 13.00,
            ministryLockedPrice: 12.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 5)),
          ),
          PharmacyStock(
            medicationId: 3,
            medicationName: 'Glucophage',
            inStock: true,
            currentPrice: 8.00,
            ministryLockedPrice: 8.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 1)),
          ),
          PharmacyStock(
            medicationId: 5,
            medicationName: 'Ventolin',
            inStock: false,
            currentPrice: 5.50,
            ministryLockedPrice: 5.50,
            lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
          ),
          PharmacyStock(
            medicationId: 9,
            medicationName: 'Brufen',
            inStock: true,
            currentPrice: 3.00,
            ministryLockedPrice: 3.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 3)),
          ),
        ],
      ),
      Pharmacy(
        id: 2,
        name: 'MedCare Pharmacy',
        location: 'Bliss Street, Ras Beirut',
        licenseNumber: 'LIC002',
        hwid: 'HWID002',
        region: 'Beirut Central',
        status: 'online',
        lastSeen: 'just now',
        latencyMs: 38,
        syncVersion: '2.6.1',
        syncPct: 100,
        createdAt: DateTime(2024, 1, 12),
        latitude: 33.8988,
        longitude: 35.4788,
        phone: '+961 1 362 000',
        rating: 4.2,
        reviewCount: 85,
        openingHours: '07:30',
        closingHours: '23:00',
        isOpen: true,
        distanceKm: 1.2,
        stock: [
          PharmacyStock(
            medicationId: 1,
            medicationName: 'Panadol',
            inStock: true,
            currentPrice: 2.75,
            ministryLockedPrice: 2.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 4)),
          ),
          PharmacyStock(
            medicationId: 4,
            medicationName: 'Lipitor',
            inStock: true,
            currentPrice: 15.00,
            ministryLockedPrice: 15.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 6)),
          ),
          PharmacyStock(
            medicationId: 6,
            medicationName: 'Zithromax',
            inStock: true,
            currentPrice: 11.50,
            ministryLockedPrice: 10.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 8)),
          ),
          PharmacyStock(
            medicationId: 7,
            medicationName: 'Nexium',
            inStock: true,
            currentPrice: 18.00,
            ministryLockedPrice: 18.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 2)),
          ),
        ],
      ),
      Pharmacy(
        id: 3,
        name: 'Pharma Plus',
        location: 'Verdun Street, Beirut',
        licenseNumber: 'LIC003',
        hwid: 'HWID003',
        region: 'Beirut South',
        status: 'online',
        lastSeen: 'just now',
        latencyMs: 52,
        syncVersion: '2.6.1',
        syncPct: 98,
        createdAt: DateTime(2024, 1, 14),
        latitude: 33.8828,
        longitude: 35.4878,
        phone: '+961 1 800 500',
        rating: 3.8,
        reviewCount: 62,
        openingHours: '09:00',
        closingHours: '21:00',
        isOpen: true,
        distanceKm: 2.1,
        stock: [
          PharmacyStock(
            medicationId: 2,
            medicationName: 'Augmentin',
            inStock: true,
            currentPrice: 12.00,
            ministryLockedPrice: 12.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 3)),
          ),
          PharmacyStock(
            medicationId: 8,
            medicationName: 'Crestor',
            inStock: false,
            currentPrice: 20.00,
            ministryLockedPrice: 20.00,
            lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
          ),
          PharmacyStock(
            medicationId: 10,
            medicationName: 'Concor',
            inStock: true,
            currentPrice: 12.50,
            ministryLockedPrice: 11.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 7)),
          ),
          PharmacyStock(
            medicationId: 11,
            medicationName: 'Amoxil',
            inStock: true,
            currentPrice: 4.50,
            ministryLockedPrice: 4.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 1)),
          ),
        ],
      ),
      Pharmacy(
        id: 4,
        name: 'City Pharmacy',
        location: 'Mar Elias, Beirut',
        licenseNumber: 'LIC004',
        hwid: 'HWID004',
        region: 'Mount Lebanon',
        status: 'online',
        lastSeen: 'just now',
        latencyMs: 35,
        syncVersion: '2.6.1',
        syncPct: 100,
        createdAt: DateTime(2024, 1, 16),
        latitude: 33.8780,
        longitude: 35.5050,
        phone: '+961 1 700 300',
        rating: 4.7,
        reviewCount: 203,
        openingHours: '08:00',
        closingHours: '00:00',
        isOpen: true,
        distanceKm: 1.5,
        stock: [
          PharmacyStock(
            medicationId: 1,
            medicationName: 'Panadol',
            inStock: true,
            currentPrice: 2.50,
            ministryLockedPrice: 2.50,
            lastUpdated: DateTime.now().subtract(const Duration(minutes: 30)),
          ),
          PharmacyStock(
            medicationId: 3,
            medicationName: 'Glucophage',
            inStock: true,
            currentPrice: 8.50,
            ministryLockedPrice: 8.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 2)),
          ),
          PharmacyStock(
            medicationId: 5,
            medicationName: 'Ventolin',
            inStock: true,
            currentPrice: 5.50,
            ministryLockedPrice: 5.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 1)),
          ),
          PharmacyStock(
            medicationId: 9,
            medicationName: 'Brufen',
            inStock: true,
            currentPrice: 3.00,
            ministryLockedPrice: 3.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 4)),
          ),
          PharmacyStock(
            medicationId: 12,
            medicationName: 'Cataflam',
            inStock: true,
            currentPrice: 6.00,
            ministryLockedPrice: 6.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 3)),
          ),
        ],
      ),
      Pharmacy(
        id: 5,
        name: 'Wellness Pharmacy',
        location: 'Jounieh Highway, Jounieh',
        licenseNumber: 'LIC005',
        hwid: 'HWID005',
        region: 'Mount Lebanon',
        status: 'online',
        lastSeen: '5 minutes ago',
        latencyMs: 62,
        syncVersion: '2.6.1',
        syncPct: 95,
        createdAt: DateTime(2024, 1, 18),
        latitude: 33.9808,
        longitude: 35.6178,
        phone: '+961 9 930 100',
        rating: 4.0,
        reviewCount: 47,
        openingHours: '08:30',
        closingHours: '20:00',
        isOpen: true,
        distanceKm: 5.3,
        stock: [
          PharmacyStock(
            medicationId: 1,
            medicationName: 'Panadol',
            inStock: true,
            currentPrice: 2.50,
            ministryLockedPrice: 2.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 6)),
          ),
          PharmacyStock(
            medicationId: 6,
            medicationName: 'Zithromax',
            inStock: false,
            currentPrice: 10.00,
            ministryLockedPrice: 10.00,
            lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
          ),
          PharmacyStock(
            medicationId: 10,
            medicationName: 'Concor',
            inStock: true,
            currentPrice: 11.00,
            ministryLockedPrice: 11.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 5)),
          ),
        ],
      ),
      Pharmacy(
        id: 6,
        name: 'Green Cross Pharmacy',
        location: 'Sassine Square, Ashrafieh',
        licenseNumber: 'LIC006',
        hwid: 'HWID006',
        region: 'Beirut East',
        status: 'online',
        lastSeen: '2 minutes ago',
        latencyMs: 48,
        syncVersion: '2.6.1',
        syncPct: 99,
        createdAt: DateTime(2024, 1, 20),
        latitude: 33.8880,
        longitude: 35.5250,
        phone: '+961 1 215 000',
        rating: 4.3,
        reviewCount: 91,
        openingHours: '07:00',
        closingHours: '22:00',
        isOpen: true,
        distanceKm: 3.0,
        stock: [
          PharmacyStock(
            medicationId: 2,
            medicationName: 'Augmentin',
            inStock: true,
            currentPrice: 12.50,
            ministryLockedPrice: 12.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 3)),
          ),
          PharmacyStock(
            medicationId: 4,
            medicationName: 'Lipitor',
            inStock: true,
            currentPrice: 16.00,
            ministryLockedPrice: 15.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 10)),
          ),
          PharmacyStock(
            medicationId: 7,
            medicationName: 'Nexium',
            inStock: true,
            currentPrice: 19.50,
            ministryLockedPrice: 18.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 4)),
          ),
          PharmacyStock(
            medicationId: 11,
            medicationName: 'Amoxil',
            inStock: true,
            currentPrice: 4.50,
            ministryLockedPrice: 4.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 2)),
          ),
          PharmacyStock(
            medicationId: 12,
            medicationName: 'Cataflam',
            inStock: false,
            currentPrice: 6.00,
            ministryLockedPrice: 6.00,
            lastUpdated: DateTime.now().subtract(const Duration(days: 3)),
          ),
        ],
      ),
      // ── North Lebanon Pharmacies ──────────────────────────────
      Pharmacy(
        id: 7,
        name: 'Al-Mina Pharmacy',
        location: 'Al-Mina Street, Tripoli',
        licenseNumber: 'LIC007',
        hwid: 'HWID007',
        region: 'North Lebanon',
        status: 'online',
        lastSeen: '10 minutes ago',
        latencyMs: 78,
        syncVersion: '2.6.0',
        syncPct: 92,
        createdAt: DateTime(2024, 1, 22),
        latitude: 34.4360,
        longitude: 35.8497,
        phone: '+961 6 432 100',
        rating: 4.4,
        reviewCount: 76,
        openingHours: '07:30',
        closingHours: '22:00',
        isOpen: true,
        distanceKm: 82.0,
        stock: [
          PharmacyStock(
            medicationId: 1,
            medicationName: 'Panadol',
            inStock: true,
            currentPrice: 2.50,
            ministryLockedPrice: 2.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 1)),
          ),
          PharmacyStock(
            medicationId: 2,
            medicationName: 'Augmentin',
            inStock: true,
            currentPrice: 12.00,
            ministryLockedPrice: 12.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 3)),
          ),
          PharmacyStock(
            medicationId: 5,
            medicationName: 'Ventolin',
            inStock: true,
            currentPrice: 5.50,
            ministryLockedPrice: 5.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 2)),
          ),
          PharmacyStock(
            medicationId: 9,
            medicationName: 'Brufen',
            inStock: true,
            currentPrice: 3.00,
            ministryLockedPrice: 3.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 4)),
          ),
          PharmacyStock(
            medicationId: 12,
            medicationName: 'Cataflam',
            inStock: false,
            currentPrice: 6.00,
            ministryLockedPrice: 6.00,
            lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
          ),
        ],
      ),
      Pharmacy(
        id: 8,
        name: 'Tripoli Central Pharmacy',
        location: 'Tall Square, Tripoli',
        licenseNumber: 'LIC008',
        hwid: 'HWID008',
        region: 'North Lebanon',
        status: 'online',
        lastSeen: '3 minutes ago',
        latencyMs: 65,
        syncVersion: '2.6.1',
        syncPct: 100,
        createdAt: DateTime(2024, 1, 24),
        latitude: 34.4400,
        longitude: 35.8420,
        phone: '+961 6 411 200',
        rating: 4.6,
        reviewCount: 142,
        openingHours: '08:00',
        closingHours: '23:00',
        isOpen: true,
        distanceKm: 83.0,
        stock: [
          PharmacyStock(
            medicationId: 3,
            medicationName: 'Glucophage',
            inStock: true,
            currentPrice: 8.00,
            ministryLockedPrice: 8.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 1)),
          ),
          PharmacyStock(
            medicationId: 4,
            medicationName: 'Lipitor',
            inStock: true,
            currentPrice: 15.50,
            ministryLockedPrice: 15.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 5)),
          ),
          PharmacyStock(
            medicationId: 6,
            medicationName: 'Zithromax',
            inStock: true,
            currentPrice: 10.00,
            ministryLockedPrice: 10.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 2)),
          ),
          PharmacyStock(
            medicationId: 10,
            medicationName: 'Concor',
            inStock: true,
            currentPrice: 11.00,
            ministryLockedPrice: 11.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 3)),
          ),
          PharmacyStock(
            medicationId: 7,
            medicationName: 'Nexium',
            inStock: false,
            currentPrice: 18.00,
            ministryLockedPrice: 18.00,
            lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
          ),
        ],
      ),
      Pharmacy(
        id: 9,
        name: 'Byblos Pharmacy',
        location: 'Old Souk Road, Jbeil (Byblos)',
        licenseNumber: 'LIC009',
        hwid: 'HWID009',
        region: 'Mount Lebanon',
        status: 'online',
        lastSeen: '8 minutes ago',
        latencyMs: 55,
        syncVersion: '2.6.0',
        syncPct: 96,
        createdAt: DateTime(2024, 1, 26),
        latitude: 34.1236,
        longitude: 35.6511,
        phone: '+961 9 540 300',
        rating: 4.1,
        reviewCount: 53,
        openingHours: '08:00',
        closingHours: '21:00',
        isOpen: true,
        distanceKm: 37.0,
        stock: [
          PharmacyStock(
            medicationId: 1,
            medicationName: 'Panadol',
            inStock: true,
            currentPrice: 2.50,
            ministryLockedPrice: 2.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 2)),
          ),
          PharmacyStock(
            medicationId: 8,
            medicationName: 'Crestor',
            inStock: true,
            currentPrice: 20.00,
            ministryLockedPrice: 20.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 6)),
          ),
          PharmacyStock(
            medicationId: 11,
            medicationName: 'Amoxil',
            inStock: true,
            currentPrice: 4.50,
            ministryLockedPrice: 4.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 1)),
          ),
          PharmacyStock(
            medicationId: 5,
            medicationName: 'Ventolin',
            inStock: false,
            currentPrice: 5.50,
            ministryLockedPrice: 5.50,
            lastUpdated: DateTime.now().subtract(const Duration(days: 1)),
          ),
        ],
      ),
      Pharmacy(
        id: 10,
        name: 'Batroun Health Pharmacy',
        location: 'Main Road, Batroun',
        licenseNumber: 'LIC010',
        hwid: 'HWID010',
        region: 'Mount Lebanon',
        status: 'online',
        lastSeen: '15 minutes ago',
        latencyMs: 71,
        syncVersion: '2.6.0',
        syncPct: 94,
        createdAt: DateTime(2024, 1, 28),
        latitude: 34.2553,
        longitude: 35.6580,
        phone: '+961 6 740 500',
        rating: 3.9,
        reviewCount: 38,
        openingHours: '08:30',
        closingHours: '20:00',
        isOpen: true,
        distanceKm: 52.0,
        stock: [
          PharmacyStock(
            medicationId: 1,
            medicationName: 'Panadol',
            inStock: true,
            currentPrice: 2.50,
            ministryLockedPrice: 2.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 3)),
          ),
          PharmacyStock(
            medicationId: 2,
            medicationName: 'Augmentin',
            inStock: true,
            currentPrice: 12.50,
            ministryLockedPrice: 12.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 5)),
          ),
          PharmacyStock(
            medicationId: 9,
            medicationName: 'Brufen',
            inStock: true,
            currentPrice: 3.00,
            ministryLockedPrice: 3.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 1)),
          ),
        ],
      ),
      Pharmacy(
        id: 11,
        name: 'Zgharta Family Pharmacy',
        location: 'Main Street, Zgharta',
        licenseNumber: 'LIC011',
        hwid: 'HWID011',
        region: 'North Lebanon',
        status: 'online',
        lastSeen: '12 minutes ago',
        latencyMs: 82,
        syncVersion: '2.5.9',
        syncPct: 90,
        createdAt: DateTime(2024, 2, 1),
        latitude: 34.3988,
        longitude: 35.8947,
        phone: '+961 6 660 200',
        rating: 4.3,
        reviewCount: 61,
        openingHours: '07:00',
        closingHours: '21:30',
        isOpen: true,
        distanceKm: 88.0,
        stock: [
          PharmacyStock(
            medicationId: 3,
            medicationName: 'Glucophage',
            inStock: true,
            currentPrice: 8.00,
            ministryLockedPrice: 8.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 2)),
          ),
          PharmacyStock(
            medicationId: 6,
            medicationName: 'Zithromax',
            inStock: true,
            currentPrice: 10.00,
            ministryLockedPrice: 10.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 4)),
          ),
          PharmacyStock(
            medicationId: 10,
            medicationName: 'Concor',
            inStock: false,
            currentPrice: 11.00,
            ministryLockedPrice: 11.00,
            lastUpdated: DateTime.now().subtract(const Duration(days: 3)),
          ),
          PharmacyStock(
            medicationId: 12,
            medicationName: 'Cataflam',
            inStock: true,
            currentPrice: 6.00,
            ministryLockedPrice: 6.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 1)),
          ),
        ],
      ),
      Pharmacy(
        id: 12,
        name: 'Cedars Pharmacy',
        location: 'Cedar Road, Bcharre',
        licenseNumber: 'LIC012',
        hwid: 'HWID012',
        region: 'North Lebanon',
        status: 'offline',
        lastSeen: '1 hour ago',
        latencyMs: 125,
        syncVersion: '2.5.8',
        syncPct: 85,
        createdAt: DateTime(2024, 2, 3),
        latitude: 34.2509,
        longitude: 36.0118,
        phone: '+961 6 671 100',
        rating: 4.0,
        reviewCount: 29,
        openingHours: '09:00',
        closingHours: '19:00',
        isOpen: false,
        distanceKm: 120.0,
        stock: [
          PharmacyStock(
            medicationId: 1,
            medicationName: 'Panadol',
            inStock: true,
            currentPrice: 2.50,
            ministryLockedPrice: 2.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 8)),
          ),
          PharmacyStock(
            medicationId: 5,
            medicationName: 'Ventolin',
            inStock: true,
            currentPrice: 5.50,
            ministryLockedPrice: 5.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 6)),
          ),
          PharmacyStock(
            medicationId: 7,
            medicationName: 'Nexium',
            inStock: false,
            currentPrice: 18.00,
            ministryLockedPrice: 18.00,
            lastUpdated: DateTime.now().subtract(const Duration(days: 4)),
          ),
        ],
      ),
      Pharmacy(
        id: 13,
        name: 'Koura Pharmacy',
        location: 'Amioun Main Road, Koura',
        licenseNumber: 'LIC013',
        hwid: 'HWID013',
        region: 'North Lebanon',
        status: 'online',
        lastSeen: '4 minutes ago',
        latencyMs: 68,
        syncVersion: '2.6.1',
        syncPct: 97,
        createdAt: DateTime(2024, 2, 5),
        latitude: 34.3000,
        longitude: 35.8167,
        phone: '+961 6 950 400',
        rating: 4.2,
        reviewCount: 44,
        openingHours: '08:00',
        closingHours: '21:00',
        isOpen: true,
        distanceKm: 73.0,
        stock: [
          PharmacyStock(
            medicationId: 1,
            medicationName: 'Panadol',
            inStock: true,
            currentPrice: 2.50,
            ministryLockedPrice: 2.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 2)),
          ),
          PharmacyStock(
            medicationId: 4,
            medicationName: 'Lipitor',
            inStock: true,
            currentPrice: 15.00,
            ministryLockedPrice: 15.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 4)),
          ),
          PharmacyStock(
            medicationId: 9,
            medicationName: 'Brufen',
            inStock: true,
            currentPrice: 3.50,
            ministryLockedPrice: 3.00,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 3)),
          ),
          PharmacyStock(
            medicationId: 11,
            medicationName: 'Amoxil',
            inStock: true,
            currentPrice: 4.50,
            ministryLockedPrice: 4.50,
            lastUpdated: DateTime.now().subtract(const Duration(hours: 1)),
          ),
          PharmacyStock(
            medicationId: 8,
            medicationName: 'Crestor',
            inStock: false,
            currentPrice: 20.00,
            ministryLockedPrice: 20.00,
            lastUpdated: DateTime.now().subtract(const Duration(days: 2)),
          ),
        ],
      ),
    ];
  }

  // ─── Reviews ────────────────────────────────────────────────
  static List<Review> getReviews() => [
    Review(
      id: 'rev_001',
      pharmacyId: '1',
      userId: 'user_001',
      userName: 'Ahmad K.',
      stockAccuracyRating: 4.5,
      serviceQualityRating: 5.0,
      comment:
          'Great pharmacy! Always has what I need and staff is very helpful.',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    Review(
      id: 'rev_002',
      pharmacyId: '1',
      userId: 'user_002',
      userName: 'Sara M.',
      stockAccuracyRating: 3.0,
      serviceQualityRating: 4.0,
      comment:
          'Good service but they were out of Ventolin last time I visited.',
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
    ),
    Review(
      id: 'rev_003',
      pharmacyId: '2',
      userId: 'user_003',
      userName: 'Omar H.',
      stockAccuracyRating: 2.0,
      serviceQualityRating: 3.5,
      comment:
          'App showed Zithromax in stock but it wasn\'t there when I went.',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      hasDiscrepancyReport: true,
      discrepancyDetails:
          'Zithromax 500mg was listed as in stock but the pharmacy had been out for 2 days.',
    ),
    Review(
      id: 'rev_004',
      pharmacyId: '4',
      userId: 'user_004',
      userName: 'Lina T.',
      stockAccuracyRating: 5.0,
      serviceQualityRating: 5.0,
      comment:
          'Best pharmacy in the area. Always accurate stock and fair prices.',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    Review(
      id: 'rev_005',
      pharmacyId: '3',
      userId: 'user_005',
      userName: 'Karim B.',
      stockAccuracyRating: 3.5,
      serviceQualityRating: 3.0,
      comment: 'Decent pharmacy but prices are sometimes above ministry rates.',
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      hasDiscrepancyReport: true,
      discrepancyDetails:
          'Concor was priced at 12.50 instead of the ministry-locked price of 11.00.',
    ),
    Review(
      id: 'rev_006',
      pharmacyId: '6',
      userId: 'user_006',
      userName: 'Nour A.',
      stockAccuracyRating: 4.0,
      serviceQualityRating: 4.5,
      comment: 'Friendly staff and clean pharmacy. Slightly pricey though.',
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
    ),
  ];

  // ─── Categories ─────────────────────────────────────────────
  static List<String> getCategories() => [
    'All',
    'Pain Relief',
    'Antibiotics',
    'Diabetes',
    'Cardiovascular',
    'Respiratory',
    'Gastrointestinal',
  ];
}
